@HostAddress = http://localhost:5206

GET {{HostAddress}}/api/dentaloffices
Accept: application/json
Authorization: Bearer CfDJ8Mo3BsyRK4pBi9ewV5v-vo8l7nVgH5u8Pn6FrHvGwKERaqneRq72o_ORZzi26ToPfBEEbrGHg_j3z1TBwlUR0ZHeG54Jj2por8q2wxtBnhDDFQeomdkcIksa0J_TO7y67938yFW4jOfWFzpMAvzgVopdF78CRw6FPTtFZso7_W97eYJ3x5p-kpE4oqsuLcAqxj_onN5DRPtk77du61GnlwanRnWgRTVTJYd7FKFVdijeIQ4rJ4eRMleCM6Jv3pIiCiDImEy9QFpQ5GWxMUjuLkSBwr0tlE2kHcLehzd_Xd683oAwJcnSRhTB1BxEuvbV3aMJBqM3JL4J2DUKHh278uk--wbF8lZBdjUyBTNgC6VM36wtoQi46ar9QR8FqTokH--24G_FHTdqRPf5fWIVHZL5CwaUx_Jj9HLBstyWUBorBiwcfRSKOws5ETZ32CrFfW1WlJXB6j-vbHRL_eyFBE1gONMD38iI4-emLD5km286OqvdfhfK9gb0hiGzCslcoO-ozRPj-xC3b0vhoFHbbAnxVnk6B5hdRAEJO9ZIh__rbndtskuWAlunme-fiV15RMBZJkfqSAd96JSfCoUebKEv4j6ug7i_F_Mg0E5LRO9TdUJnValA3klM092YJiD76pyHCdC48YMx2rhk1osepwjZmHQ1OCyj2an9EOAgrFnNqhI8lpjvIiLa2HiYr465sQinffjUJZAynL9tNDcYypkHzoA0gJwYUsc7fb7Zr_ev

###

GET {{HostAddress}}/api/dentaloffices/b985fc98-6071-4695-a5da-655beb104809
Accept: application/json

###

POST {{HostAddress}}/api/dentaloffices
Content-Type: application/json
Authorization: Bearer CfDJ8Mo3BsyRK4pBi9ewV5v-vo8l7nVgH5u8Pn6FrHvGwKERaqneRq72o_ORZzi26ToPfBEEbrGHg_j3z1TBwlUR0ZHeG54Jj2por8q2wxtBnhDDFQeomdkcIksa0J_TO7y67938yFW4jOfWFzpMAvzgVopdF78CRw6FPTtFZso7_W97eYJ3x5p-kpE4oqsuLcAqxj_onN5DRPtk77du61GnlwanRnWgRTVTJYd7FKFVdijeIQ4rJ4eRMleCM6Jv3pIiCiDImEy9QFpQ5GWxMUjuLkSBwr0tlE2kHcLehzd_Xd683oAwJcnSRhTB1BxEuvbV3aMJBqM3JL4J2DUKHh278uk--wbF8lZBdjUyBTNgC6VM36wtoQi46ar9QR8FqTokH--24G_FHTdqRPf5fWIVHZL5CwaUx_Jj9HLBstyWUBorBiwcfRSKOws5ETZ32CrFfW1WlJXB6j-vbHRL_eyFBE1gONMD38iI4-emLD5km286OqvdfhfK9gb0hiGzCslcoO-ozRPj-xC3b0vhoFHbbAnxVnk6B5hdRAEJO9ZIh__rbndtskuWAlunme-fiV15RMBZJkfqSAd96JSfCoUebKEv4j6ug7i_F_Mg0E5LRO9TdUJnValA3klM092YJiD76pyHCdC48YMx2rhk1osepwjZmHQ1OCyj2an9EOAgrFnNqhI8lpjvIiLa2HiYr465sQinffjUJZAynL9tNDcYypkHzoA0gJwYUsc7fb7Zr_ev

{
  "name": "Dental Office D"
}

###

PUT {{HostAddress}}/api/dentaloffices/e59c0da0-63a7-4a82-94e7-1d4c3ca1ef15
Content-Type: application/json
Authorization: Bearer CfDJ8Mo3BsyRK4pBi9ewV5v-vo8l7nVgH5u8Pn6FrHvGwKERaqneRq72o_ORZzi26ToPfBEEbrGHg_j3z1TBwlUR0ZHeG54Jj2por8q2wxtBnhDDFQeomdkcIksa0J_TO7y67938yFW4jOfWFzpMAvzgVopdF78CRw6FPTtFZso7_W97eYJ3x5p-kpE4oqsuLcAqxj_onN5DRPtk77du61GnlwanRnWgRTVTJYd7FKFVdijeIQ4rJ4eRMleCM6Jv3pIiCiDImEy9QFpQ5GWxMUjuLkSBwr0tlE2kHcLehzd_Xd683oAwJcnSRhTB1BxEuvbV3aMJBqM3JL4J2DUKHh278uk--wbF8lZBdjUyBTNgC6VM36wtoQi46ar9QR8FqTokH--24G_FHTdqRPf5fWIVHZL5CwaUx_Jj9HLBstyWUBorBiwcfRSKOws5ETZ32CrFfW1WlJXB6j-vbHRL_eyFBE1gONMD38iI4-emLD5km286OqvdfhfK9gb0hiGzCslcoO-ozRPj-xC3b0vhoFHbbAnxVnk6B5hdRAEJO9ZIh__rbndtskuWAlunme-fiV15RMBZJkfqSAd96JSfCoUebKEv4j6ug7i_F_Mg0E5LRO9TdUJnValA3klM092YJiD76pyHCdC48YMx2rhk1osepwjZmHQ1OCyj2an9EOAgrFnNqhI8lpjvIiLa2HiYr465sQinffjUJZAynL9tNDcYypkHzoA0gJwYUsc7fb7Zr_ev

{
  "name": "Dental Office D - Updated"
}

###

DELETE {{HostAddress}}/api/dentaloffices/bae4b354-fd80-46dc-a40c-f1dcb013d473
Content-Type: application/json

{
  "name": "Dental Office A - Updated"
}