@HostAddress = http://localhost:5206

GET {{HostAddress}}/api/dentaloffices
Accept: application/json
Authorization: Bearer CfDJ8Mo3BsyRK4pBi9ewV5v-vo9R5SEmyWunP1buAbUUaV9hzp2WHwTOvhtrmFZuC21th9oiSbXSTP_zj3KNBLZa2_PAUEfdt3vLoQQ1TJbgiKBzdupZqQRPd605pk4GES63fn5a2oK3pN_IWcBcowXdokmS_28fhrlq28-r6EPq_bb-dqOjDFwedmPYParWhIsokaeaFnzaDyFeGZs2sM4cyIgEGzh5Yg-BEEvzmM7cJOUAUjvfBM0jP8wm1kPrI27Lf7uX7ChqnwrZafw9n-I5Ylo9Cd1KGefBR2Ug_j_uiHKC2-y4sY0GpHmvkskTYsFWzEhN-k7onI2l8H6Dsip4zXQ23P-G7chH-4uaUVzB2O1pNmyfH_Wn2S53LUvdgTewXAdVyjDtScVot0CRdzVjrdC_rFBAfshWMQbgnzTHMhY-cRzx_DkWaWlwcbzx8BdLheb3QeAlQ8JwDEyx_SqP_svtGLfGxMaTjbj51Vsyo2RFFSQWaJnpcWYDRf_YM-7nOOgznSp2eFPMhOqY0OqrnaJIyzgLSHVUyp7hNzBHEc5e57bhvPXKou23OC1YxtnoUkvXmtozUdd9mRCuoUWErau8H2AaPbuXVKAiyJxeJVCPMA4i7OL3ASClxA5hUewqxviSQjt2yePXa9ul7mP3P0sn2kZIRCSu4ZsqFh1CEyFZ8tiNLcaTKmgVCrvsJHSd6MvKKYVS1kvVeq5rTCqMOKvr7FEeMrTChA2LiR07nq-m

###

GET {{HostAddress}}/api/dentaloffices/b985fc98-6071-4695-a5da-655beb104809
Accept: application/json

###

POST {{HostAddress}}/api/dentaloffices
Content-Type: application/json
Authorization: Bearer CfDJ8Mo3BsyRK4pBi9ewV5v-vo9R5SEmyWunP1buAbUUaV9hzp2WHwTOvhtrmFZuC21th9oiSbXSTP_zj3KNBLZa2_PAUEfdt3vLoQQ1TJbgiKBzdupZqQRPd605pk4GES63fn5a2oK3pN_IWcBcowXdokmS_28fhrlq28-r6EPq_bb-dqOjDFwedmPYParWhIsokaeaFnzaDyFeGZs2sM4cyIgEGzh5Yg-BEEvzmM7cJOUAUjvfBM0jP8wm1kPrI27Lf7uX7ChqnwrZafw9n-I5Ylo9Cd1KGefBR2Ug_j_uiHKC2-y4sY0GpHmvkskTYsFWzEhN-k7onI2l8H6Dsip4zXQ23P-G7chH-4uaUVzB2O1pNmyfH_Wn2S53LUvdgTewXAdVyjDtScVot0CRdzVjrdC_rFBAfshWMQbgnzTHMhY-cRzx_DkWaWlwcbzx8BdLheb3QeAlQ8JwDEyx_SqP_svtGLfGxMaTjbj51Vsyo2RFFSQWaJnpcWYDRf_YM-7nOOgznSp2eFPMhOqY0OqrnaJIyzgLSHVUyp7hNzBHEc5e57bhvPXKou23OC1YxtnoUkvXmtozUdd9mRCuoUWErau8H2AaPbuXVKAiyJxeJVCPMA4i7OL3ASClxA5hUewqxviSQjt2yePXa9ul7mP3P0sn2kZIRCSu4ZsqFh1CEyFZ8tiNLcaTKmgVCrvsJHSd6MvKKYVS1kvVeq5rTCqMOKvr7FEeMrTChA2LiR07nq-m

{
  "name": "Dental Office D"
}

###

PUT {{HostAddress}}/api/dentaloffices/e59c0da0-63a7-4a82-94e7-1d4c3ca1ef15
Content-Type: application/json
Authorization: Bearer CfDJ8Mo3BsyRK4pBi9ewV5v-vo9R5SEmyWunP1buAbUUaV9hzp2WHwTOvhtrmFZuC21th9oiSbXSTP_zj3KNBLZa2_PAUEfdt3vLoQQ1TJbgiKBzdupZqQRPd605pk4GES63fn5a2oK3pN_IWcBcowXdokmS_28fhrlq28-r6EPq_bb-dqOjDFwedmPYParWhIsokaeaFnzaDyFeGZs2sM4cyIgEGzh5Yg-BEEvzmM7cJOUAUjvfBM0jP8wm1kPrI27Lf7uX7ChqnwrZafw9n-I5Ylo9Cd1KGefBR2Ug_j_uiHKC2-y4sY0GpHmvkskTYsFWzEhN-k7onI2l8H6Dsip4zXQ23P-G7chH-4uaUVzB2O1pNmyfH_Wn2S53LUvdgTewXAdVyjDtScVot0CRdzVjrdC_rFBAfshWMQbgnzTHMhY-cRzx_DkWaWlwcbzx8BdLheb3QeAlQ8JwDEyx_SqP_svtGLfGxMaTjbj51Vsyo2RFFSQWaJnpcWYDRf_YM-7nOOgznSp2eFPMhOqY0OqrnaJIyzgLSHVUyp7hNzBHEc5e57bhvPXKou23OC1YxtnoUkvXmtozUdd9mRCuoUWErau8H2AaPbuXVKAiyJxeJVCPMA4i7OL3ASClxA5hUewqxviSQjt2yePXa9ul7mP3P0sn2kZIRCSu4ZsqFh1CEyFZ8tiNLcaTKmgVCrvsJHSd6MvKKYVS1kvVeq5rTCqMOKvr7FEeMrTChA2LiR07nq-m

{
  "name": "Dental Office D - Updated"
}

###

DELETE {{HostAddress}}/api/dentaloffices/bae4b354-fd80-46dc-a40c-f1dcb013d473
Content-Type: application/json

{
  "name": "Dental Office A - Updated"
}