@HostAddress = http://localhost:5206

GET {{HostAddress}}/api/dentists?page=1&recordsPerpage=4&name=
Accept: application/json

###

GET {{HostAddress}}/api/dentists/0255bf08-ee0c-4c0b-af2c-39f2b27cf557
Accept: application/json

###

POST {{HostAddress}}/api/dentists
Content-Type: application/json

{
  "name": "",
  "email": "123"
}

###

PUT {{HostAddress}}/api/dentists/0255bf08-ee0c-4c0b-af2c-39f2b27cf557
Content-Type: application/json

{
  "name": "Dentist B2",
  "Email": "db2@example.com"
}

###

DELETE {{HostAddress}}/api/dentists/f0753643-862c-4f70-8384-6e70d0b1b9cf
Content-Type: application/json
